[book]
    title = "Shreyas' Wiki"
    description = "Assorted notes and guides"
    author = "Shreyas Minocha"
    language = "en"
    multilingual = false
    src = "src"

[output.html]
    curly-quotes = true
    mathjax-support = true
    no-section-label = true
    git-repository-url = "https://github.com/shreyasminocha/wiki"
    additional-css = ["custom/docco.css", "custom/style.css"]
    additional-js = ["custom/mathjax.js"]

[output.html.fold]
    enable = true
    level = 1

[output.html.playpen]
    copyable = false
    copy-js = false

[output.html.search]
    enable = false
